# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luana-web
email: tester-git@outlook.com
description: > # this means to ignore newlines until "baseurl:"
 Este é o blog da Luana, desenvolvedora front end, e pessoa linda nas horas vagas.
baseurl: "/luana-web" # the subpath of your site, e.g. /blog
url: "http://luana-silva.github.io" # the base hostname & protocol for your site # Entender isso
twitter_username: luana_twitter
github_username:  luana-silva

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
# permalink: /palavra/:title
permalink: /:title

